import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <>
  <meta charSet="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Alumni | School Record</title>
  <link
    rel="shortcut icon"
    href="assets/images/favicon.png"
    type="image/x-icon"
  />
  {/* all css file include  */}
  <link rel="stylesheet" href="assets/css/bootstrap.min.css" />
  <link rel="stylesheet" href="assets/css/animate.css" />
  <link rel="stylesheet" href="assets/css/slick.css" />
  <link rel="stylesheet" href="assets/css/boxicons.css" />
  <link rel="stylesheet" href="assets/css/main.css" />
  <link rel="stylesheet" href="assets/css/responsive.css" />
  <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
</>

{/* <!-- all js file include  --> */}

<script src="assets/js/jQuery.js"></script>
  <script src="assets/js/bootstrap.bundle.js"></script>
  <script src="assets/js/slick.min.js"></script>
  <script src="assets/js/wow.js"></script>
  <script src="assets/js/main.js"></script>

      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
